AllCops:
  Exclude:
    - "vendor/**/*"
    - pairs.gemspec
  NewCops: enable

# Style/StringLiterals:
#   Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
