AllCops:
  Exclude:
    - "vendor/**/*"
    - hexlet-pairs.gemspec
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
